name = "alice-predictions-worker"
main = "dist/_worker.js"
compatibility_date = "2024-09-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "eth-trader-production"
database_id = "a8f40259-2dc1-4c5c-9c5e-8b4a8c8e5c5a"

[env.production.vars]
COINGECKO_API_KEY = "CG-x5dWQp9xfuNgFKhSDsnipde4"