name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Alice Predictions Trading App
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: alice-predictions
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
  validate-deployment:
    needs: deploy
    runs-on: ubuntu-latest
    name: Validate Deployment
    
    steps:
      - name: Test API endpoints
        run: |
          echo "Testing Alice Predictions API endpoints..."
          
          # Test health endpoint
          curl -f https://alice-predictions.pages.dev/api/health || echo "Health check failed"
          
          # Test market data endpoints
          curl -f https://alice-predictions.pages.dev/api/market/ETH || echo "ETH endpoint failed"
          curl -f https://alice-predictions.pages.dev/api/market/BTC || echo "BTC endpoint failed"
          
          # Test prediction endpoints  
          curl -f https://alice-predictions.pages.dev/api/predictions/ETH || echo "ETH predictions failed"
          curl -f https://alice-predictions.pages.dev/api/predictions/BTC || echo "BTC predictions failed"
          
          # Test automation endpoints (UptimeRobot ready)
          curl -f https://alice-predictions.pages.dev/api/automation/hourly || echo "Hourly automation failed"
          curl -f https://alice-predictions.pages.dev/api/trading/check-positions || echo "Position monitoring failed"
          
          echo "Deployment validation completed!"